@sandeep
Feature: Cabelas

	Scenario: Checkout on cabelas
		Given I am on "https://www.cabelas.com" site
		When I click on ".signInText"
			And I click on ".icon-headerSignInBtn"
		Then I should see "Remember"
		When I fill in "userName" with "04070bc6@opayq.com"
			And I fill in "password" with "Cvxkf2xmsdqY"
			And I click on link id "#logInBtn"
		Then I should see "JOHN"
		Given I am on items page "http://www.cabelas.com/catalog/product.jsp?productId=2286581&categoryId=0&parentCategoryId=0&subCategoryId=0&indexId=0&itemGUID=2966d6e2ac10845547dc69a7f54cc460"
		Then I should see "Price"
		When I click on ".btnAddToCart"
		Then I should see "Item Added to Cart"
		Given I set id for ".summaryColumn img"
		When I click on link id "#blurclick"
		Then I should see "Remove"
		When I click on ".greenButton"
		Then I should see "ENTER PAYMENT METHOD"
		When I click on link id "#addCreditCardText"
		Then I should see "First Name"
		When I fill in "firstName" with "John"
			And I fill in "lastName" with "Moe"
			And I fill in "ccNumber" with "4111111111111111"
			And I select "10" in "#ccMonth"
			And I select "2024" in "#ccYear"
			And I fill in "cvv" with "465"
			And I click on link id "#navbarBottom1"
		Then I should see "EDIT BILLING NAME AND ADDRESS"
		When I fill in "firstName" with "John"
			And I fill in "lastName" with "Moe"
			And I fill in "address1" with "280 summer st"
			And I fill in "address2" with "FL 3"
			And I fill in "city" with "Boston"
			And I select "MA" in "#state"
			And I fill in "zipCode" with "02210"
			And I fill in "phoneNumber" with "6052223254"
			And I fill in "emailAddress" with "04070bc6@opayq.com"