@sandeep
Feature: Childrensplace
	
	Scenario: Checkout on childrensplace
		Given I am on "https://www.childrensplace.com/shop/LogonForm?catalogId=10551&myAcctMain=1&langId=-1&storeId=10151" site
		When I click on ".ui-icon-closethick"
		Then I should see "Forgot password"
		When I fill in "logonId1" with "a7d2a6ae@opayq.com"
			And I fill in "logonPassword1" with "3gjx7aqdHfaM"
			And I click on link id "#WC_AccountDisplay_links_2"
		Then I should see "John"
		When I click on link id "#guestShopperContinue1"
		Then I should see "SHIPPING ADDRESS"
		When I fill in "firstName" with "John"
			And I fill in "lastName" with "Moe"
			And I fill in "address1" with "280 summer st"
			And I fill in "address2" with "#3"
			And I fill in "city" with "Boston"
			And I select "MA" in "#WC_TCPShippingAddress_FormInput_state"
			And I fill in "addressField3" with "02210"
			And I fill in "phone1" with "6052224458"
			And I select "901101" in "#singleShipmentShippingMode"
			And I click on link id "#shippingBillingPageNext"
		Then I should see "You Entered"
		When I click on text "Use As Entered" with ".ui-button-text"
		Then I should see "BILLING ADDRESS"
		When I fill in "firstName" with "John"
			And I fill in "lastName" with "Moe"
			And I fill in "address1" with "280 summer st"
			And I fill in "address2" with "FL 3"
			And I fill in "city" with "Boston"
			And I select "MA" in "#WC_TCPShippingAddress_FormInput_state"
			And I fill in "addressField3" with "02210"
			And I fill in "phone1" with "6052224458"
			And I click on link id ".pay-credit-card #cardImage"
			And I select "COMPASSVISA" in "#payMethodId"
			And I fill in "account1" with "4111111111111111"
			And I fill in "cc_cvc" with "456"
			And I select "10" in "#expire_month"
			And I select "2024" in "#expire_year"
			