@sandeep
Feature: Colehann
	
	Scenario: Checkout on colehann
		Given I am on "http://www.colehaan.com/" site
		When I click on ".ui-dialog-titlebar-close"
			And I click on link id "#account-login"
		Then I should see "REMEMBER ME"
		Given I set id for ".email-input"
		When I fill in "blurclick" with "c5884a9c@opayq.com"
		Given I set id1 for ".password-input"
		When I fill in "blurclick1" with "vkjLgb4h3vwG"
			And I click on ".login-button"
			And I click on ".shopping-bag"
		Then I should see "PRODUCT"
		When I click on ".tracking-checkout-anon"
		Then I should see "Shipping Address"
		When I fill in "dwfrm_coaddress_shippingAddress_firstName" with "John"
			And I fill in "dwfrm_coaddress_shippingAddress_lastName" with "Moe"
			And I fill in "dwfrm_coaddress_shippingAddress_address1" with "280 summer st"
			And I fill in "dwfrm_coaddress_shippingAddress_address2" with "FL 3"
			And I fill in "dwfrm_coaddress_shippingAddress_city" with "Boston"
			And I select "MA" in "#dwfrm_coaddress_shippingAddress_states_state"
			And I fill in "dwfrm_coaddress_shippingAddress_zip" with "02210"
			And I fill in "dwfrm_coaddress_shippingAddress_phone" with "6052223256"
			And I fill in "dwfrm_coaddress_billingAddress_firstName" with "John"
			And I fill in "dwfrm_coaddress_billingAddress_lastName" with "Moe"
			And I fill in "dwfrm_coaddress_billingAddress_address1" with "280 summer st"
			And I fill in "dwfrm_coaddress_billingAddress_address2" with "FL 3"
			And I fill in "dwfrm_coaddress_billingAddress_city" with "Boston"
			And I select "MA" in "#dwfrm_coaddress_billingAddress_states_state"
			And I fill in "dwfrm_coaddress_billingAddress_zip" with "02210"
			And I fill in "dwfrm_coaddress_billingAddress_billingPhone" with "6052223256"
			And I fill in "dwfrm_coaddress_billingAddress_emailAddress" with "c5884a9c@opayq.com"
			And I click on ".blue-button"
		Then I should see "Checkout"
		When I click on link id "#dwfrm_copayment_paymentMethods_creditCard_type1"
		Then I should see "Name on Card"
		When I fill in "dwfrm_copayment_paymentMethods_creditCard_owner" with "John Moe"
			And I fill in "dwfrm_copayment_paymentMethods_creditCard_number" with "4111111111111111"
			And I select "10" in "#dwfrm_copayment_paymentMethods_creditCard_month"
			And I select "2024" in "#dwfrm_copayment_paymentMethods_creditCard_year"
			And I fill in "dwfrm_copayment_paymentMethods_creditCard_cvn" with "456"