@sandeep
Feature: Disneystore

	Scenario: Checkout on disneystore
		Given I am on "http://www.disneystore.com/" site
		When I click on ".signinPopupTrigger"
		Then I should see "Forgot your"
		When I fill in "returningEmailAddress" with "41a700d6@opayq.com"
			And I fill in "newCustPassword" with "3nskneupVpyH"
			And I click on link id "#signInButton"
		Then I should see "We've put all your items together"
		When I click on ".button"
			And I click on link id "#ghBag"
		Then I should see "Product Total"
			And I click on ".checkoutButton"
		Then I should see "Quantity"
		When I click on ".checkOutButton"
		Then I should see "Choose the Address"
		Given I set id for ".editDeliveryButton a"
		When I click on link id "#blurclick"
		Then I should see "Edit Address"
		When I fill in "firstNameInput" with "John"
			And I fill in "lastNameInput" with "Moe"
			And I fill in "address1Input" with "280 summer st"
			And I fill in "address2Input" with "FL 3"
			And I fill in "zipcodeInput" with "02210"
			And I fill in "phone1Input" with "6052223254"
			And I click on link id "#SaveContinue"
		Then I should see "Choose Delivery Method"
		When I click on link id "#continueToPayButton"
		Then I should see "Enter Secure Payment"
		When I fill in "CCName_On_CardInput" with "John"
			And I fill in "CCCredit_Card_Number" with "4111111111111111"
			And I select "10" in "#CC_ccmonths"
			And I select "2024" in "#CC_ccyears"
			And I fill in "CC_cvv" with "465"