@sandeep
Feature: Eastbay

	Scenario: Checkoput on eastbay
		Given I am on "http://www.eastbay.com/" site
		When I click on link id "#header_account_link"
		Then I should see "LOG IN"
		When I fill in "login_email" with "fca58406@maskmemail.com"
			And I fill in "login_password" with "42xjhcgAlP"
			And I click on link id "#login_submit"
		Then I should see "ACCOUNT"
		Given I am on items page "http://www.eastbay.com/shoppingcart/default.cfm?sku="
		When I click on link id "#attention_continue"
		Then I should see "CART"	
		When I click on link id "#cart_checkout_button"
		Then I should see "Please enter your credit card number"
		When I fill in "CardNumber" with "4111111111111111"
			And I fill in "CardExpireDateMM" with "10"
			And I fill in "CardExpireDateYY" with "24"
			And I fill in "CardCCV" with "458"
			And I click on link id "#billPaneEdit"
		Then I should see "FIRST NAME"
		When I fill in "billFirstName" with "John"
			And I fill in "billLastName" with "Moe"
			And I fill in "billAddress1" with "280 summer st"
			And I fill in "billAddress2" with "FL 3"
			And I fill in "billPostalCode" with "02210"
			And I fill in "billCity" with "Boston"
			And I select "MA" in "#billState"
			And I fill in "billHomePhone" with "6052223214"
		Then I sleep for 5 sec
		When I click on link id "#shipPaneEdit"
		Then I should see "VERIFY YOUR ADDRESS"
		When I click on link id "#address_verification_use_original_button"
		Then I should see "FIRST NAME"
			And I fill in "shipFirstName" with "John"
			And I fill in "shipLastName" with "Moe"
			And I fill in "shipAddress1" with "280 summer st"
			And I fill in "shipAddress2" with "FL 3"
			And I fill in "shipPostalCode" with "02210"
			And I fill in "shipCity" with "Boston"
			And I select "MA" in "#shipState"
			And I fill in "shipHomePhone" with "6052223214"
			