@sandeep
Feature: Fender

	Scenario: Checkout on fender
		Given I am on "https://shop.fender.com/en-US/account" site
		Then I should see "RETURNING CUSTOMERS"
		When I fill in id ".login-account .email-input" with "8567bdb4@opayq.com"
			And I fill in id ".login-account 	.password-input" with "uxwvm4ezWlhG"
			And I click on ".arrow-circle"
		Then I should see "MY ACCOUNT"
		When I click on ".mini-cart-total"
		Then I should see "SHOPPING CART"
		When I click on ".arrow-circle"
		Then I should see "SHIPPING ADDRESS"
		When I fill in "dwfrm_singleshipping_shippingAddress_addressFields_firstName" with "John"
			And I fill in "dwfrm_singleshipping_shippingAddress_addressFields_lastName" with "Moe"
			And I fill in "dwfrm_singleshipping_shippingAddress_addressFields_address1" with "280 summer st"
			And I fill in "dwfrm_singleshipping_shippingAddress_addressFields_address2" with "FL 3"
			And I fill in "dwfrm_singleshipping_shippingAddress_addressFields_city" with "Boston"
			And I select "MA" in "#dwfrm_singleshipping_shippingAddress_addressFields_states_state"
			And I fill in "dwfrm_singleshipping_shippingAddress_addressFields_zip" with "02210"
			And I fill in "dwfrm_singleshipping_shippingAddress_addressFields_phone" with "6052224458"
			And I click on link id "#dwfrm_singleshipping_shippingAddress_useAsBillingAddress"
		Then I sleep for 5 sec
		When I click on ".arrow-circle"
		Then I should see "PAYMENT METHOD"
		When I fill in "dwfrm_billing_paymentMethods_creditCard_owner" with "John Moe"
			And I fill in "dwfrm_billing_paymentMethods_creditCard_number" with "4111111111111111"
			And I select "10" in "#dwfrm_billing_paymentMethods_creditCard_month"
			And I select "2024" in "#dwfrm_billing_paymentMethods_creditCard_year"
			And I fill in "dwfrm_billing_paymentMethods_creditCard_cvn" with "456"
			And I fill in "dwfrm_billing_billingAddress_addressFields_firstName" with "John"
			And I fill in "dwfrm_billing_billingAddress_addressFields_lastName" with "Moe"
			And I fill in "dwfrm_billing_billingAddress_addressFields_address1" with "280 summer st"
			And I fill in "dwfrm_billing_billingAddress_addressFields_address2" with "FL 3"
			And I fill in "dwfrm_billing_billingAddress_addressFields_city" with "Boston"
			And I select "MA" in "#dwfrm_billing_billingAddress_addressFields_states_state"
			And I fill in "dwfrm_billing_billingAddress_addressFields_zip" with "02210"
			And I fill in "dwfrm_billing_billingAddress_addressFields_phone" with "6052224458"