@sandeep
Feature: Frontgate

	Scenario: Checkout on frontgate
		Given I am on "https://www.frontgate.com/" site
		When I click on href "/UserLogonView"
			And I click on href "/UserLogonView?storeId=10053&catalogId=10053&langId=-1"
			And I click on ".gwt_welcome_window_close"
		Then I should see "Remember me"
		When I fill in "logonId" with "fed36778@opayq.com"
			And I fill in "logonPassword" with "a3kjfwhL0syY"
			And I click on link id "#logonButton"
		Then I should see "John"
		When I click on link id "#shoppingCart"
		Then I should see "Remove"
		When I click on text "Begin Checkout" with ".spot .button"
		Then I should see "Special Delivery Terms & Conditions"
		When I fill in "bestPhoneNumber" with "6052223214"
		When I click on ".okCancelPanel .primary"
		Then I should see "Billing Address"
		When I click on text "Edit Billing Address" with ".button"
		Then I should see "First Name"
		When I fill in "addr_fnbox" with "John"
			And I fill in "addr_lnbox" with "Moe"
			And I fill in "addr_sa1box" with "280 summer st"
			And I fill in "addr_sa2box" with "FL 3"
			And I fill in "addr_citybox" with "Boston"
			And I select "MA" in "#addr_region"
			And I fill in "addr_zipbox" with "02210"
			And I fill in "addr_phone1box" with "6052223254"
			And I fill in "addr_phone2box" with "6052223255"
			And I click on ".secondary"
		Then I should see "PAYMENT INFORMATION"
		When I select "Visa" in "#payMethodCCID"
			And I fill in "accountcc" with "4111111111111111"
			And I fill in "card_id_number" with "465"
			And I select "10" in "#expire_month"
			And I select "2024" in "#expire_year"
			