@sandeep
Feature: HM

	Scenario: Checkout on hm
		Given I am on "http://www.hm.com/us/" site
		When I click on ".close"
			And I click on link id "#bar-login"
		Then I should see "Returning customer"
		When I fill in "username" with "52e38ba2@opayq.com"
			And I fill in "password" with "5tdm0zyhSdaD"
			And I click on link id "#loginButton"
		Then I should see "Welcome"
		When I click on link id "#bar-bag"
		Then I should see "SHOPPING BAG"
			And I clear cart if I see "Remove" and I click on ".removeFast" and I dont do anything if I see "Your shopping bag is still empty"
		Given I am on items page "http://www.hm.com/us/product/90859?article=90859-B"
		Then I should see "PRODUCT DESCRIPTION"
		When I click on link id "#btn-addToBag"
			And I click on link id "#bar-bag"
		Then I should see "SHOPPING BAG"
		When I click on "#bagTotal .btn"
		Then I should see "CHECKOUT"
		When I click on "#deliveryOptionsComponent .status"
		Then I should see "SELECT DELIVERY METHOD"
			And I click on text "Change delivery address" with ".action"
		Then I should see "CHANGE ADDRESS"
		When I click on text "Edit Address" with ".action"
			And I fill in "addressLine1" with "280 summer st"
			And I fill in "alternativeDeliveryAddress-addressLine2" with "FL 3"
			And I fill in "city" with "Boston"
			And I select "21" in "#alternativeDeliveryAddress-region"
			And I fill in "postCode" with "02210"
			And I click on ".overlay .close"
			And I click on link id "#btn-submit-order"
		Then I should see "Card number"
		When I fill in "input-cardNumber" with "4111111111111111"
			And I select "10" in "#input-expiryMonth"
			And I select "2024" in "#input-expiryYear"
			And I fill in "input-cardCode" with "456"
			And I click on link id "#input-addressChoiceOther"
		Then I should see "Address line 1"
		When I fill in "input-addressStreet" with "280 summer st"
			And I fill in "input-redCustAddr2" with "FL 3"
			And I fill in "input-addressCity" with "Boston"
			And I select "MA" in "ADDRESS.STATE"
			And I fill in "input-addressZip" with "02210"
			