@sandeep
Feature: Jcrew

	Scenario: Checkout on jcrew
		Given I am on "https://www.jcrew.com/signin/signin.jsp" site
		Then I should see "Keep me signed in"
		When I fill in "loginUser" with "cae73420@opayq.com"
			And I fill in "loginPassword" with "xwhnA24veA"
			And I click on ".button-submit"
		#Then I should see "Sign up for emails"
		#When I click on ".closePopup"
		Then I should see "MY ACCOUNT"
			And I click on link id "#globalHeaderShoppingBagBttn2"
		Then I should see "SHOPPING BAG"
		When I click on link id "#button-checkout"
		Then I should see "SHIPPING ADDRESS"
		When I click on ".item-edit"
		Then I should see "EDIT YOUR SHIPPING"
		When I fill in "ADDRESS<>firstName" with "John"
			And I fill in "ADDRESS<>lastName" with "Moe"
			And I fill in "ADDRESS<>address1" with "280 summer st"
			And I fill in "ADDRESS<>address2" with "FL 3"
			And I fill in "ADDRESS<>postal" with "02210"
			And I fill in "ADDRESS<>phone" with "6052223256"
			And I click on ".force-link"
			And I click on ".button-submit"
		Then I should see "CHOOSE A SHIPPING METHOD"
		When I click on ".button-submit"
		Then I should see "ENTER YOUR CARD DETAILS"
		When I fill in "CREDIT_CARD<>cardNum" with "4111111111111111"
			And I fill in "CREDIT_CARD<>cardVerifyNum" with "465"
			And I select "10" in "#expirationMonth"
			And I select "2,024" in "#expirationYear"
			And I fill in "CREDIT_CARD<>cardholderName" with "John Moe"