@sandeep
Feature: Lakeside

	Scenario: Checkout on lakeside
		Given I am on "https://www.lakeside.com/my_account/index.jsp" site
		When I click on ".close-reveal-modal"
		Then I should see "Returning Customers"
		When I fill in "login-email" with "6f6f7c7d@opayq.com"
			And I fill in "login-password" with "xjkYyzqbeq7E"
			And I click on ".resp_btn_brand_s"
		Then I should see "John"
		When I click on ".cart-button"
		Then I should see "Shopping Cart"
			And I clear cart if I see "Remove" and I click on ".removeItem" and I dont do anything if I see "Your Cart is empty"
		Given I am on items page "http://www.lakeside.com/Toys---Electronics/Outdoor-Toys/Set-of-2-Bumper-Balls/27lh/prod2010478.jmp?categoryId=cat52215"
		Then I should see "Print This Page"
		When I click on ".add-to-cart"
			And I click on ".cart-button"
		Then I should see "Shopping Cart"
		When I click on ".resp_btn_green"
		Then I should see "Shipping Address"
		When I click on link id "#addEditAddress"
			And I fill in "address-firstName" with "John"
			And I fill in "address-lastName" with "Moe"
			And I fill in "address-address1" with "280 summer st"
			And I fill in "address-address2" with "FL 3"
			And I fill in "address-city" with "Boston"
			And I select "MA" in "#address-state"
			And I fill in "address-postalCode" with "02210"
			And I fill in "address-phoneNumber" with "6052221254"
			And I click on ".resp_msg_il_sm"
			And I click on link id "#formSubmitButton"
		Then I should see "Pay with Credit Card"
		When I click on link id "#selectCreditCard"
			And I fill in "cardholderName-field" with "John Moe"
			And I fill in "creditCardNumber-field" with "4111111111111111"
			And I fill in "creditCardSecurity" with "456"
			And I select "10" in "#creditCardExpirationDate-Month"
			And I select "2024" in "#creditCardExpirationDate-Year"
			And I fill in "billingAddress-firstName" with "John"
			And I fill in "billingAddress-lastName" with "Moe"
			And I fill in "billingAddress-address1" with "280 summer st"
			And I fill in "billingAddress-address2" with "FL 3"
			And I fill in "billingAddress-city" with "Boston"
			And I select "MA" in "#billingAddress-state"
			And I fill in "billingAddress-postalCode" with "02210"