@sandeep
Feature: Landofnod

	Scenario: Checkout on landofnod
		Given I am on "https://www.landofnod.com/account/login.aspx#r=%2fdefault.aspx" site
		When I click on ".ui-dialog-titlebar-close"
		Then I should see "Remember me"
		When I fill in "_email" with "4471dff3@opayq.com"
			And I fill in "_password" with "hasxwe2sOU"
			And I click on link id "#_submitSignin"
		Then I should see "John"
		When I click on link id "#_cartButtonHeader"
		Then I should see "Item Price"
		When I click on link id "#btnProceedToCheckoutTop"
		Then I should see "Ship to"
		When I click on ".edit-text"
		Then I should see "First Name"
		When I fill in "firstName" with "John"
			And I fill in "lastName" with "Moe"
			And I fill in "address1" with "280 summer st"
			And I fill in "address2" with "FL 3"
			And I fill in "zipCodeNumber" with "0221"
			And I fill in "daytimePhone" with "6052223256"
			And I click on ".dialog-close-icon"
			And I click on ".btn-delivery-continue"
		Then I should see "Card Number"
		When I fill in "AppliedCreditCard.CreditCardNumber" with "4111111111111111"
			And I select "10" in "#AppliedCreditCard_ExpirationMonth"
			And I select "2024" in "#AppliedCreditCard_ExpirationYear"
			And I fill in "AppliedCreditCard.SecurityCode" with "458"
			And I click on ".edit-text"
		Then I should see "First Name"
		When I fill in "BillingAddress.CurrentAddress.FirstName" with "John"
			And I fill in "BillingAddress.CurrentAddress.LastName" with "Moe"
			And I fill in "CurrentAddress.Address1" with "280 summer st"
			And I fill in "BillingAddress.CurrentAddress.Address2" with "FL 3"
			And I fill in "City" with "Boston"
			And I select "MA" in "#State"
			And I fill in "zipCodeNumber" with "0221"
			And I fill in "txtBillAMPhone" with "6052223256"
			And I fill in "txtBillEmail" with "4471dff3@opayq.com"