@sandeep
Feature: Luckybrand

	Scenario: Checkout on luckybrand
		Given I am on "http://www.luckybrand.com/" site
		Then I should see "ALREADY A MEMBER"
		When I click on link id "#popup-subcription-closes-link-6927ecb0-9c75-4a0c-838c-91ac635db1fe"
			And I click on ".user-login"
			And I fill in id ".email-input" with "99c1a6af@opayq.com"
			And I fill in id ".password-input" with "n7k8rxonrvBD"
			And I click on ".account-login-submit"
		Then I should see "John"
		Given I am on items page "https://www.luckybrand.com/cart"
		Then I should see "REMOVE"
		When I click on ".checkout-btns .button-fancy-large"
		Then I should see "SELECT OR ENTER A SHIPPING ADDRESS"
		When I fill in "dwfrm_singleshipping_shippingAddress_addressFields_firstName" with "John"
			And I fill in "dwfrm_singleshipping_shippingAddress_addressFields_lastName" with "Moe"
			And I fill in "dwfrm_singleshipping_shippingAddress_addressFields_address1" with "280 summer st"
			And I fill in "dwfrm_singleshipping_shippingAddress_addressFields_address2" with "FL 3"
			And I fill in "dwfrm_singleshipping_shippingAddress_addressFields_city" with "Boston"
			And I select "MA" in "#dwfrm_singleshipping_shippingAddress_addressFields_states_state"
			And I fill in "dwfrm_singleshipping_shippingAddress_addressFields_zip" with "02210"
			And I fill in "dwfrm_singleshipping_shippingAddress_addressFields_phone" with "6052223254"
		Then I sleep for 5 sec
		When I click on ".checkout-btns .checkoutbutton"
		Then I should see "SELECT OR ENTER A BILLING ADDRESS"
		When I fill in "dwfrm_billing_billingAddress_addressFields_firstName" with "John"
			And I fill in "dwfrm_billing_billingAddress_addressFields_lastName" with "Moe"
			And I fill in "dwfrm_billing_billingAddress_addressFields_address1" with "280 summer st"
			And I fill in "dwfrm_billing_billingAddress_addressFields_address2" with "FL 3"
			And I fill in "dwfrm_billing_billingAddress_addressFields_city" with "Boston"
			And I select "MA" in "#dwfrm_billing_billingAddress_addressFields_states_state"
			And I fill in "dwfrm_billing_billingAddress_addressFields_zip" with "02210"
			And I fill in "dwfrm_billing_billingAddress_addressFields_phone" with "6052223254"
			And I fill in "dwfrm_billing_billingAddress_email_emailAddress" with "99c1a6af@opayq.com"
			And I fill in "dwfrm_billing_paymentMethods_creditCard_owner" with "John Moe"
			And I select "Visa" in "#dwfrm_billing_paymentMethods_creditCard_type"
			And I fill in "dwfrm_billing_paymentMethods_creditCard_numberinput" with "4111111111111111"
			And I select "10" in "#dwfrm_billing_paymentMethods_creditCard_month"
			And I select "2024" in "#dwfrm_billing_paymentMethods_creditCard_year"
			And I fill in "dwfrm_billing_paymentMethods_creditCard_cvn" with "468"