@sandeep
Feature: Microsoft
	
	Scenario: Checkout on microsoft
		Given I am on items page "http://www.microsoftstore.com/store/msusa/en_US/pdp/Dell-XPS-13-9350-5340SLV-Core-i7-256GB-Signature-Edition-Laptop/productID.326872100"
		When I click on ".mfp-close"
		Then I should see "Dell XPS"
		When I click on ".buyBtn_AddtoCart"
		Then I should see "Buy Office"
		When I click on ".mfp-close"
		Then I should see "Added to your cart"
		When I click on ".review-checkout-wrapper .btn-extended"
		Then I should see "Cart"
		When I click on ".cart-header .checkout"
		Then I should see "New Customer"
		When I click on ".btn-guest-checkout"
		Then I should see "Email my receipt to"
		When I fill in "guestEmail" with "cd5aaffb4@opayq.com"
			And I fill in "guestConfirmEmail" with "cd5aaffb4@opayq.com"
			And I fill in "shippingName1" with "John"
			And I fill in "shippingName2" with "Moe"
			And I fill in "shippingAddress1" with "280 summer st"
			And I fill in "shippingAddress2" with "FL 3"
			And I fill in "shippingCity" with "Boston"
			And I select "MA" in "#shippingState"
			And I fill in "shippingPostalCode" with "02210"
			And I fill in "shippingPhoneNumber" with "6052223256"
			And I click on ".checkout-extended"
		Then I sleep for 5 sec
		Given I switch to iframe "pcsframe"
		Then I should see "PayPal"
		When I fill in "creditCardNumber" with "4111111111111111"
			And I select "10" in "#creditCardExpireMonth"
			And I select "2024" in "#creditCardExpireYear"
			And I fill in "creditCardHolderName" with "John Moe"
			And I fill in "cvm" with "458"
			And I fill in "billingAddress1" with "280 summer st"
			And I fill in "billingAddress2" with "FL 3"
			And I fill in "billingCity" with "Boston"
			And I select "MA" in "#billingState"
			And I fill in "billingZipcode" with "02210"
			And I fill in "billingPhonePrefix" with "605"
			And I fill in "billingPhoneNumber" with "2327895"
		
		