@sandeep
Feature: Musiciansfriend

	Scenario: Checkout on musiciansfriend
		Given I am on "https://www.musiciansfriend.com/myaccount/login?" site
		Then I should see "Log-In"
		When I fill in "returningCustomer_Email" with "3cb0519a@opayq.com"
			And I fill in "returningCustomer_Password" with "Ack9wgtd3mhD"
		Given I am on items page "http://www.musiciansfriend.com/accessories/m-audio-sp-2-sustain-pedal"
		Then I should see "Your Price"
		When I click on ".plus-text"
		Then I should see "No, Thanks"
		When I click on ".close"
		Then I should see "Shopping Cart"
		When I click on link id "#proceedToCheckoutTop"
		Then I should see "Returning Customer"
		When I click on link id "#guestSubmit"
		Then I should see "Shipping Address"
		When I fill in "firstName" with "John"
			And I fill in "lastName" with "Moe"
			And I fill in "address1" with "280 summer st"
			And I fill in "address2" with "FL 3"
			And I fill in "city" with "Boston"
			And I select "MA" in "#state"
			And I fill in "postalCode" with "02210"
			And I press enter and fill in "phoneNumber" with "6052223254"
			And I fill in "email" with "3cb0519a@opayq.com"
			And I click on ".submit"
		Then I should see "Items To Ship"
		When I click on link id "#group0_method01"
			And I click on link id "#deliverySubmit"
		Then I should see "Payment Information"
		When I fill in "cardNumber" with "4111111111111111"
			And I select "10" in "#expMonth"
			And I select "2024" in "#expYear"
			And I fill in "securityCode" with "254"			