@sandeep
Feature: Nashbar

	Scenario: Checkout on nashbar
		Given I am on "https://www.nashbar.com/" site
		When I click on link id "#login-logoff"
		Then I should see "Forgot Password"
		When I fill in "logonId" with "1b58f24a@opayq.com"
			And I fill in "logonPassword" with "mdgvlm9ub7MD"
			And I click on ".login-login-page"
		Then I should see "JOHN"
		When I click on link id "#itemsInCart"
		Then I should see "Shopping cart"
		When I click on ".secure-checkout-button"
		Then I should see "Billing Address"
		When I fill in "billing_firstName" with "John"
			And I fill in "billing_lastName" with "Moe"
			And I fill in "billing_address1" with "280 summer st"
			And I fill in "billing_address2" with "FL 3"
			And I fill in "billing_city" with "Boston"
			And I select "MA" in "#billing_state"
			And I fill in "billing_zipCode" with "02210"
			And I fill in "billing_phone1" with "6052223254"
			And I click on link id "#WC_BillingAddressDisplay_FormInput_shipToSelection_In_BillAddressForm_3"
		Then I should see "First name"
		When I fill in "shipping_firstName" with "John"
			And I fill in "shipping_lastName" with "Moe"
			And I fill in "shipping_address1" with "280 summer st"
			And I fill in "shipping_address2" with "FL 3"
			And I fill in "shipping_city" with "Boston"
			And I select "MA" in "#shipping_state"
			And I fill in "shipping_zipCode" with "02210"
			And I fill in "shipping_phone1" with "6052223254"
			And I click on ".secure-checkout-button"
		Then I should see "Shipping Method"
		When I click on ".secure-checkout-button"
		Then I should see "Payment"
		When I select "VISA" from "paymentMethod"
			And I fill in "cc_nameoncard" with "John Moe"
			And I fill in "account" with "4111111111111111"
			And I select "10" in "#PIInfo_3_expire_month"
			And I select "2024" in "#PIInfo_3_expire_year"
			And I fill in "cc_cvc" with "465"