@sandeep
Feature: Newegg
	
	Scenario: Checkout on newegg
		Given I am on "http://www.newegg.com/" site
		When I click on link id "#usaSite"
			And I fill in "UserName" with "b01222ae@opayq.com"
			And I fill in "UserPwd" with "ltbszcbwC1nM"
			And I click on link id "#submit"
		Given I am on items page "http://www.newegg.com/Product/Product.aspx?Item=N82E16889624013&ignorebbr=1"
		When I click on ".call-to-action-main-product"
			And I click on ".fa-shopping-cart"
		Then I should see "My Shopping Cart"
		When I click on ".call-to-action-shopping-cart .has-icon-right"
		Then I should see "Shipping Address"
		When I click on text "Enter a new shipping address" with ".inline"
		Then I should see "First Name"
		When I fill in "SFirstName" with "John"
			And I fill in "SLastName" with "Moe"
			And I fill in "SAddress1" with "280 summer st"
			And I fill in "SAddress2" with "FL 3"
			And I fill in "SCity" with "Boston"
			And I select "MA" in "#SState_Option_USA"
			And I fill in "SZip" with "02210"
			And I fill in "ShippingPhone" with "6052223214"
			And I click on text "Use a saved shipping address" with ".inline"
		Then I should see "untitled"
		When I click on ".call-to-action-checkout .has-icon-right"
		Then I should see "Payment Methods"
		When I fill in "Card_HolderNameNew" with "John Moe"
			And I fill in "Card_CCNUMBERNEW" with "4111111111111111"
			And I select "10" in "#Card_exp_monthNew"
			And I select "2024" in "#Card_exp_yearNew"
			And I fill in "cvv2code" with "456"