@sandeep
Feature: Nike

	Scenario: Checkout on nike
		Given I am on "http://www.nike.com/us/en_us/" site
		When I click on ".login-text"
		Then I should see "LOG IN TO NIKE"
		When I fill in "email" with "5cffe246@opayq.com"
			And I fill in "password" with "o9Aulm8wnyxV"
			And I click on ".exp-login-submit"
		Then I should see "John Moe"
		When I click on ".nsg-glyph--cart"
		Then I should see "Continue Shopping"
			And I clear cart if I see "Qty" and I click on ".js-removeProduct" and I dont do anything if I see "There are no items in your cart"
		Given I am on items page "http://store.nike.com/us/en_us/pd/unrest-p-sunglasses/pid-11099462/pgid-11099463"
		Then I should see "Rate this product"
		When I click on ".js-add-to-cart"
			And I click on ".nsg-glyph--cart"
		Then I should see "Continue Shopping"
		When I click on link id "#ch4_cartCheckoutBtn"
		Then I should see "CHECKOUT"
		When I click on link id "#ch4_editShipping"
		Then I should see "PRIMARY ADDRESS"
		When I click on ".js-addressEdit"
		Then I should see "First Name"
		When I fill in "fname" with "John"
			And I fill in "lname" with "Moe"
			And I fill in "address1Field" with "280 summer st"
			And I fill in "address2Field" with "FL 3"
			And I fill in "city" with "Boston"
			And I select "MA" in "#singleState"
			And I fill in "postalCodeField" with "02210"
			And I click on link id "#saveNuse"
		Then I should see "Default"
		When I click on link id "#shippingSubmit"
		Then I sleep for 5 sec
		Given I switch to iframe "billingFormFrame"
		Then I should see "Card Number"
		When I fill in "creditCardNumber" with "4111111111111111"
			And I select "10" in "#expirationMonth"
			And I select "2024" in "#expirationYear"
			And I fill in "cvNumber" with "458"
			And I click on ".noTransform"
		Then I should see "First Name"
		When I fill in "firstName" with "John"
			And I fill in "lastName" with "Moe"
			And I fill in "address1" with "280 summer st"
			And I fill in "address2" with "FL 3"
			And I fill in "city" with "Boston"
			And I select "MA" in "#usState"
			And I fill in "postalCode" with "02210"
			And I fill in "phoneNumber" with "6052223256"
		
		