@sandeep
Feature: Overstock

	Scenario: Checkout on overstock
		Given I am on "https://www.overstock.com/myaccount?TID=SIGNIN" site
		When I fill in "loginEmailInput" with "1aec273b@opayq.com"
			And I fill in "loginPasswordInput" with "dcctDb6ygneY"
			And I click on ".success"
		Then I should see "Hi, John"
		When I click on ".btn-checkout-img"
		Then I should see "Billing Address"
		When I click on link id "#billing-change-trigger"
		Then I should see "Address Book"
		When I click on ".plus-image"
		Then I should see "Add an Address"
		When I fill in "AddBillingFirstName" with "John"
			And I fill in "AddBillingLastName" with "Moe"
			And I fill in "AddBillingAddress1" with "280 summer st"
			And I fill in "AddBillingAddress2" with "FL 3"
			And I fill in "AddBillingZipCode" with "02210"
			And I fill in "AddBillingCity" with "Boston"
			And I select "MA" in "#AddBillingState"
			And I fill in "AddBillingDaytimePhone" with "6052223256"
			And I click on link id "#cancelEdit"
			And I click on link id "#shipping-change-trigger"
			And I click on ".plus-image"
			And I fill in "AddShippingFirstName" with "John"
			And I fill in "AddShippingLastName" with "Moe"
			And I fill in "AddShippingAddress1" with "280 summer st"
			And I fill in "AddShippingAddress2" with "FL 3"
			And I fill in "AddShippingZipCode" with "02210"
			And I fill in "AddShippingCity" with "Boston"
			And I select "MA" in "#AddShippingState"
			And I fill in "AddShippingDaytimePhone" with "6052223256"
			And I click on link id "#cancelEdit"
		Then I should see "Payment Information"
		When I fill in "CC_number" with "4111111111111111"
			And I select "10" in "#exp_month"
			And I select "2024" in "#exp_year"