@sandeep
Feature: Petco

	Scenario: Checkout on petco
		Given I am on "http://www.petco.com/shop/en/petcostore" site
		When I click on link id "#signInUrl"
		Then I should see "Remember Me"
		When I fill in "logonId" with "7b25d956@opayq.com"
			And I fill in "logonPassword" with "c8bUbfrpvlcL"
			And I click on link id "#WC_AccountDisplay_links_2"
		Then I should see "john"
		When I click on ".glyphicon-shopping-cart"
		Then I should see "shopping cart"
		When I click on link id "#enter-promo-code"
			And I click on ".cart-checkout-btn"
		Then I should see "shipping address"
		When I click on text "add a new shipping address"
		Then I should see "add new shipping address"
		When I fill in "firstName" with "John"
			And I fill in "lastName" with "Moe"
			And I fill in "address1" with "280 summer st"
			And I fill in "address2" with "FL 3"
			And I fill in "city" with "Boston"
			And I select "MA" in "#shipping-address-state"
			And I fill in "zipCode" with "02210"
			And I fill in "phone1" with "6052223254"
			And I click on ".close"
			And I click on ".checkout-btn"
		Then I should see "shipping method"
		When I click on ".checkout-btn"
		Then I should see "Choose a payment method"
		When I click on text "Add a new credit card"
		Then I should see "Add New Card"
			And I sleep for 5 sec
		Given I set name for ".modal-content iframe" iframe
		Given I switch to iframe "blurFrame"
		Then I should see "Name on Card"
		When I fill in "FullName" with "John Moe"
			And I fill in "AccountNumber" with "4111111111111111"
			And I select "10" in "#ExpirationMonth"
			And I select "2024" in "#ExpirationYear"
			And I fill in "SecurityCode" with "465"
			And I click on link id "#SameAsShippingContainer"
		Then I should see "Address Line 1"
		When I fill in "NewAddress_AddressLine1" with "280 summer st"
			And I fill in "NewAddress_AddressLine2" with "FL 3"
			And I fill in "NewAddress_City" with "Boston"
			And I select "MA" in "#NewAddress_StateProvince"
			And I fill in "NewAddress_PostalCode" with "02210"