@sandeep
Feature: Ralphlauren

	Scenario: Checkout on ralphlauren
		Given I am on "http://www.ralphlauren.com/home/index.jsp?direct" site
		When I click on js ".monetate_lightbox_close_0"
			And I click on "#accountsel a"
		Then I should see "RETURNING CUSTOMER"
		When I fill in "emailId" with "96fab92a@opayq.com"
			And I fill in "passwd" with "loo2qrSrpyzY"
			And I click on value "Sign In"
		Then I should see "HELLO"
		When I click on href "/cart/index.jsp?ab=global_bag"
		Then I should see "REMOVE"
		When I click on ".ie-adjust"
		Then I should see "SHIPPING"
		When I choose "shipOpt1"
		Then I should see "FIRST NAME"
		When I fill in "shippingAddress.address.firstName" with "John"
			And I fill in "shippingAddress.address.lastName" with "Moe"
			And I fill in "shippingAddress.address.address1" with "280 summer st"
			And I fill in "shippingAddress.address.address2" with "FL 3"
			And I fill in "shippingAddress.address.city" with "Boston"
			And I fill in "shippingAddress.address.state" with "MA"
			And I fill in "shippingAddress.address.postalCode" with "02210"
			And I fill in "shippingAddress.phone" with "6052223256"
			And I choose "chooseBA2"
		Then I should see "FIRST NAME"
		When I fill in "billingAddress.address.firstName" with "John"
			And I fill in "billingAddress.address.lastName" with "Moe"
			And I fill in "billingAddress.address.address1" with "280 summer st"
			And I fill in "billingAddress.address.address2" with "FL 3"
			And I fill in "billingAddress.address.city" with "Boston"
			And I fill in "billingAddress.address.state" with "MA"
			And I fill in "billingAddress.address.postalCode" with "02210"
			And I fill in "billingAddress.phone" with "6052223256"
			And I choose "shipOption.editAddress_14354100286"
			And I choose "chooseBA14354100286"
		When I click on ".ie-adjust"
		Then I should see "CHECKOUT"
		When I click on ".ie-adjust"
		Then I should see "SELECT A PAYMENT METHOD"
		When I select "VC" in ".cardType"
			And I fill in "creditCardPaymentMethod.cardNumber" with "4111111111111111"			
			And I fill in "creditCardPaymentMethod.ccvNumber" with "456"			
			And I select "10" in "#expMonth"
			And I select "2024" in ".yearField"