@sandeep
Feature: Reebok
	
	Scenario: Checkout on reebok
		Given I am on "https://www.reebok.com/on/demandware.store/Sites-Reebok-US-Site/en_US/MyAccount-CreateOrLogin" site
		Then I should see "LOG IN/REGISTER"
		Given I switch to iframe "loginaccountframe"
		Then I should see "Remember me"
		When I fill in "username" with "1d59cd2d@opayq.com"
			And I fill in "password" with "gpd8nezJ1bbG"
			And I click on link id "#signinSubmit"
		Given I switch to default content
		Then I should see "JOHN"
		When I click on link id "#minicart"
		Then I should see "YOUR CART"
			And I clear cart if I see "Delete" and I click on ".delete_link" and I dont do anything if I see "There are no products in your shopping cart"
		Given I am on items page "http://www.reebok.com/us/avon-39-pink-ribbon-sport-top-water-bottle/BH5165.html"
		Then I should see "Send to a Friend"
		When I click on ".addtocartbutton"
		Then I should see "YOUR CART"
		When I click on link id "#dwfrm_cart_checkoutCart"
		Then I should see "SHIPPING ADDRESS"
		When I click on ".show_edit_address"
			And I fill in "dwfrm_delivery_singleshipping_shippingAddress_addressFields_firstName" with "John"
			And I fill in "dwfrm_delivery_singleshipping_shippingAddress_addressFields_lastName" with "Moe"
			And I fill in "dwfrm_delivery_singleshipping_shippingAddress_addressFields_address1" with "280 summer st"
			And I fill in "dwfrm_delivery_singleshipping_shippingAddress_addressFields_address2" with "FL 3"
			And I fill in "dwfrm_delivery_singleshipping_shippingAddress_addressFields_city" with "Boston"
			And I select "MA" in "#dwfrm_delivery_singleshipping_shippingAddress_addressFields_countyProvince"
			And I fill in "dwfrm_delivery_singleshipping_shippingAddress_addressFields_zip" with "02210"
			And I fill in "dwfrm_delivery_singleshipping_shippingAddress_addressFields_phone" with "6052223254"
			And I click on ".ffCheckbox"
			And I click on ".co-delivery-summary .show_edit_address"
			And I fill in "dwfrm_delivery_billing_billingAddress_addressFields_firstName" with "John"
			And I fill in "dwfrm_delivery_billing_billingAddress_addressFields_lastName" with "Moe"
			And I fill in "dwfrm_delivery_billing_billingAddress_addressFields_address1" with "280 summer st"
			And I fill in "dwfrm_delivery_billing_billingAddress_addressFields_address2" with "FL 3"
			And I fill in "dwfrm_delivery_billing_billingAddress_addressFields_city" with "Boston"
			And I select "MA" in "#dwfrm_delivery_billing_billingAddress_addressFields_countyProvince"
			And I fill in "dwfrm_delivery_billing_billingAddress_addressFields_zip" with "02210"
			And I fill in "dwfrm_delivery_billing_billingAddress_addressFields_phone" with "6052223254"
			And I click on link id "#dwfrm_delivery_savedelivery"
		Then I should see "PAYMENT METHOD"
		When I fill in "dwfrm_payment_creditCard_owner" with "John Moe"
			And I fill in "dwfrm_payment_creditCard_number" with "4111111111111111"
			And I select "10" in "#dwfrm_payment_creditCard_month"
			And I select "2024" in "#dwfrm_payment_creditCard_year"
			And I fill in "dwfrm_payment_creditCard_cvn" with "465"