@sandeep
Feature: RestoraionHardware
	
	Scenario: Checkout on RestoraionHardware
		Given I am on "https://www.restorationhardware.com" site
		When I click on ".close"
			And I click on href "/my-account/sign-in.jsp?link=topnav_signin"
		Then I should see "REMEMBER ME"
		When I fill in "emailaddress" with "e36eb749@opayq.com"
			And I fill in "/atg/userprofiling/ProfileFormHandler.value.password" with "pfwsk6Zatt4V"
			And I click on ".button--primary"
		Then I should see "HI KAPIL"
		When I click on link id "#util-cart"
		Then I should see "RESOURCES"
			And I clear cart if I see "Remove" and I click on ".order-item-qty-link" and I dont do anything if I see "YOUR SHOPPING CART IS EMPTY"
		Given I am on items page "https://www.restorationhardware.com/catalog/product/product.jsp?productId=prod2480419&categoryId=cat3850041"
		When I select "1" in ".qtyInput"
			And I click on link id "#add-button"
		Then I should see "ADDED TO YOUR CART"
		When I click on ".modal-title-bar-tall .close"
			And I click on link id "#util-cart"
		Then I should see "RESOURCES"
		When I click on ".group-notflush-bottom .js-checkout"
		Then I should see "Become a member"
		When I click on link id "#member-no-thanks"
		Then I should see "SHIPPING ADDRESS"
		When I click on ".trigger-edit-link"
		Then I should see "First Name"
		When I fill in "shippingFirstName" with "John"
			And I fill in "shippingLastName" with "Moe"
			And I fill in "shippingAddress1" with "280 summer st"
			And I fill in "shippingAddress2" with "FL 3"
			And I fill in "shippingCity" with "Boston"
			And I select "MA" in "#shippingStateDropdown" 
			And I fill in "shippingPostalCode" with "02210"
			And I click on link id "#trigger-submit-avs"
		Then I should see "PAYMENT METHOD"
		When I select "visa" in "#cardType"
			And I fill in "payment-ccnumber" with "4111111111111111"
			And I fill in "payment-cvnumberinput" with "465"
			And I select "10" in "#exp_month"
			And I select "2024" in "#exp_year"
		