@sandeep
Feature: Sierratradingpost

	Scenario: Checkout on sierratradingpost
		Given I am on "https://www.sierratradingpost.com/myaccount/login/" site
		Then I should see "Log in"
		When I fill in "LoginEditor_LoginUsername" with "2d2b8140@opayq.com"
			And I fill in "LoginEditor_LoginPassword" with "8dpoXbhxzR"
			And I click on "#myAccountLoginForm .submitButton"
			And I click on ".i-cart"
		Then I should see "Shopping"
		When I click on "#cartSummary .btn--highlighted"
		Then I should see "First Name"
		When I fill in "ShippingAddress_FirstName" with "John"
			And I fill in "ShippingAddress_LastName" with "Moe"
			And I fill in "ShippingAddress_Street1" with "280 summer st"
			And I fill in "ShippingAddress_Street2" with "FL 3"
			And I fill in "ShippingAddress_City" with "Boston"
			And I select "MA" in "#ShippingAddress_Province"
			And I fill in "ShippingAddress_PostalCode" with "02210"
			And I click on ".btn--lg"
		Then I should see "How would you like to pay"
		When I click on ".iconCheckout--visa"
		Then I should see "Credit Card Number"
		When I fill in "OrderPayments_CreditCardPayment_NumberDisplay" with "4111111111111111"
			And I select "10" in "#OrderPayments_CreditCardPayment_ExpirationDate_Month"
			And I select "2024" in "#OrderPayments_CreditCardPayment_ExpirationDate_Year"
			And I fill in "OrderPayments_CreditCardPayment_SecurityCode" with "458"
			And I fill in "BillingAddress_FirstName" with "John"
			And I fill in "BillingAddress_LastName" with "Moe"
			And I fill in "BillingAddress_Street1" with "280 summer st"
			And I fill in "BillingAddress_Street2" with "FL 3"
			And I fill in "BillingAddress_City" with "Boston"
			And I select "MA" in "#BillingAddress_Province"
			And I fill in "BillingAddress_PostalCode" with "02210"