@sandeep
Feature: Soma
	
	Scenario: Checkout on soma
		Given I am on "https://www.soma.com/store/account/login.jsp" site
		When I click on ".modalClose"
		Then I should see "Forgot Your Password"
		When I fill in "login" with "4ecc5fbd@opayq.com"
			And I fill in "password" with "tbc1Ckqqu1jV"
			And I click on alt "Sign In"
		Then I should see "John"
		Given I am on items page "https://www.soma.com/store/checkout/checkout2.jsp"
		Then I should see "Payment Information"
		When I fill in "co-billing-credit-card-number" with "4111111111111111"
			And I select "Visa" in "#co-billing-credit-card-type"
			And I select "10" in "#co-billing-credit-card-exp-month"
			And I select "2024" in "#co-billing-credit-card-exp-year"
			And I fill in id ".co-billing-credit-card-cvv" with "456"
			And I click on link id "#co-billing-save-address"
		Then I should see "First Name"
		When I fill in "billingForm_fName" with "John"
			And I fill in "billingForm_lName" with "Moe"
			And I fill in "billingForm_add1" with "280 summer st"
			And I fill in "billingForm_add2" with "FL 3"
			And I fill in "billingForm_city_hidden" with "Boston"
			And I select "MA" in "#billingForm_state_hidden"
			And I fill in "billingForm_zip" with "02210"
			And I fill in "co-billing-phone1" with "605"
			And I fill in "co-billing-phone2" with "222"
			And I fill in "co-billing-phone3" with "4458"
			And I click on link id "#modalEditShippingAddress"
		Then I should see "Edit Shipping Address"
		When I fill in "shipEdit_fName" with "John"
			And I fill in "shipEdit_lName" with "Moe"
			And I fill in "shipEdit_add1" with "280 summer st"
			And I fill in "shipEdit_add2" with "FL 3"
			And I fill in "shipEdit_city_hidden" with "Boston"
			And I select "MA" in "#shipEdit_state_hidden"
			And I fill in "shipEdit_zip" with "02210"
			And I fill in "co-shipping-phone1" with "605"
			And I fill in "co-shipping-phone2" with "222"
			And I fill in "co-shipping-phone3" with "4458"