@sandeep
Feature: Ulta

	Scenario: Checkout on ulta
		Given I am on "https://www.ulta.com/ulta/myaccount/login.jsp" site
		Then I should see "RETURNING GUESTS"
		When I fill in "login" with "3da9861b@opayq.com"
			And I fill in "password" with "Wm0wzevw4F"
			And I click on ".signin-button"
		Then I should see "HI"
		Given I am on items page "http://www.ulta.com/ulta/cart/cart.jsp"
		Then I should see "MY BAG"
		When I click on ".checkout"
		Then I should see "A LITTLE SOMETHING EXTRA"
		When I click on ".nosamples"
		Then I should see "SHIPPING INFORMATION"
		When I click on ".shipping-edit-address"
		Then I should see "EDIT ADDRESS"
		When I fill in "shippingFirstName" with "John"
			And I fill in "shippingLastName" with "Moe"
			And I fill in "shippingAddress1" with "280 summer st"
			And I fill in "shippingAddress2" with "FL 3"
			And I fill in "shippingCity" with "Boston"
			And I select "MA" in "#shippingState"
			And I fill in "shippingZip" with "02210"
			And I fill in "shippingPhone" with "6052224458"
			And I click on ".dismisslink"
			And I click on ".continue-shipping"
		Then I should see "Address Verification"
		When I click on ".keep"
		Then I should see "SHIPPING METHOD"
		When I click on link id "#finalShipSubmit"
		Then I should see "PAYMENT INFORMATION"
		When I fill in "nameOnCardAdd" with "John Moe"
			And I fill in "creditCardNumberAdd" with "4111111111111111"
			And I fill in "creditCardVerificationNumber2" with "456"
			And I select "10" in "#dropdown-measurement-select-3"
			And I select "2024" in "#dropdown-measurement-select-4"
			And I click on ".payment-edit-address"
		Then I should see "EDIT ADDRESS"
		When I fill in "billingFirstName" with "John"
			And I fill in "billingLastName" with "Moe"
			And I fill in "billingAddress1" with "280 summer st"
			And I fill in "billingAddress2" with "FL 3"
			And I fill in "billingCity" with "Boston"
			And I select "MA" in "#billingState"
			And I fill in "billingZip" with "02210"
			And I fill in "billingPhoneNumber" with "6052224458"