@sandeep
Feature: Uncommongoods
	
	Scenario: Checkout on uncommongoods
		Given I am on "http://www.uncommongoods.com/" site 
		When I click on ".icon-account"
		Then I should see "Forgot your password"
		When I fill in "loginEmailAddress" with "01aff28c@abinemail.com"
			And I fill in "loginPassword" with "syl9hd4ysxDF"
			And I click on link id "#signInFormSubmit"
		Then I should see "Hi"
		When I click on link id "#checkoutButton"
		Then I should see "Item"
		When I click on ".continueCheckout"
		Then I should see "Enter your password"
		When I fill in "verifyPassword" with "syl9hd4ysxDF"
			And I click on value "load my info"
		Then I should see "Billing Address"
		When I fill in "bFirstName" with "John"
			And I fill in "bLastName" with "Moe"
			And I fill in "bStreetAddress" with "280 summer st"
			And I fill in "bAptBuildingSuite" with "FL 3"
			And I fill in "bZipCode" with "02210"
			And I fill in "bCity" with "Boston"
			And I select "80:1:MA" in "#bState"
			And I fill in "bPhoneFirst" with "6052223254"
			And I fill in "bEmailAddress" with "01aff28c@abinemail.com"
			And I fill in "sFirstName" with "John"
			And I fill in "sLastName" with "Moe"
			And I fill in "sStreetAddress" with "280 summer st"
			And I fill in "sAptBuildingSuite" with "FL 3"
			And I fill in "sZipCode" with "02210"
			And I fill in "sCity" with "Boston"
			And I select "80:1:MA" in "#sState"
			And I fill in "sPhoneFirst" with "6052223254"
			And I click on link id "#sShipMethodIdStandard"
			And I click on ".continueCheckout"
		Then I should see "Pay with Credit/Debit Card"
		When I fill in "ccNumber" with "4111111111111111"
			And I select "10" from "ccExpireMonth"
			And I select "2024" from "ccExpireYear"
			And I fill in "cvv" with "465"