@sandeep
Feature: Westelm
	
	Scenario: Checkout on westelm
		Given I am on "https://secure.westelm.com/account/login.html" site
		Then I should see "Forgot your password"
		When I fill in "login-email" with "ea86dcc9@opayq.com"
			And I fill in "login-password" with "gmxdxsQsd8wA"
			And I click on link id "#btn-sign-in"
		Then I should see "John"
		When I click on link id "#checkout-button"
		Then I should see "Shopping Cart"
		When I click on ".checkoutButton"
		Then I should see "Shipping Address"
		When I click on text "Edit" with ".overlayTrigger"
		Then I should see "Edit Address"
		When I fill in "address.fullName" with "John Moe"			
			And I fill in "address.addrLine1" with "280 summer st"
			And I fill in "address.addrLine2" with "FL 3"
			And I fill in "address.city" with "Boston"
		Given I set id for ".region select"
		When I select "MA" in "#blurclick"
			And I fill in "address.zip" with "02210"
			And I fill in "address.dayPhone" with "6052224458"
			And I click on link id "#overlayCloseButton"
			And I fill in "shipTo.address.fullName" with "John Moe"
			And I fill in "shipTo.address.addrLine1" with "280 summer st"
			And I fill in "shipTo.address.addrLine2" with "FL 3"
			And I fill in "shipTo.address.city" with "Boston"
		Given I set id for ".select-state"
		When I select "MA" in "#blurclick"
			And I fill in "shipTo.address.zip" with "02210"
			And I fill in "shipTo.address.dayPhone" with "6052224458"
			And I click on ".address-card-use-this-address"
		Then I should see "Shipping Method"
		When I click on ".btn-mondo"
		Then I should see "Backorder"
		When I click on ".button-group .btn-primary"
		Then I should see "Credit Card Information"
		Given I set id for ".grouped-inputs-third select"
		When I select "5" in "#blurclick"
			And I fill in "creditCard.cardNumber" with "4111111111111111"
			And I select "10" in ".exp-month"
			And I select "2024" in ".exp-year"
			And I fill in "creditCard.cardVerificationNumber" with "456"