@sandeep
Feature: Zulily

	Scenario: Checkout on zulily
		Given I am on "http://www.zulily.com/" site
		Then I should see "Already a member"
		Given I set id for ".register-footer a"
		When I click on link id "#blurclick"
		Then I should see "SIGN IN"
		When I fill in "email" with "gahaajg@opayq.com"
			And I fill in "login-password" with "zhzjzkxkjuoq9"
			And I click on ".shop_now"
			And I click on ".icon-basket"
		Then I should see "SHOPPING BASKET"
			And I clear cart if I see "remove" and I click on ".btn-remove" and I dont do anything if I see "Your basket is empty"
		Given I am on items page "http://www.zulily.com/p/bianca-green-her-daily-motivation-throw-pillow-186237-37329564.html?pos=9&fromEvent=186237&"
		When I click on ".btn-danger"
		Then I sleep for 5 sec
			And I should see "BASKET"
		When I click on ".icon-basket"
		Then I should see "SHOPPING BASKET"
		When I click on ".proceed-to-checkout"
		Then I should see "SHIPPING ADDRESS"
		When I click on ".current_address"
		Then I should see "Add a new address"
		When I click on ".edit"
		Then I should see "First name"
		When I fill in "address[firstname]" with "John"
			And I fill in "address[lastname]" with "Moe"
			And I fill in "address[street1]" with "280 summer st"
			And I fill in "address[street2]" with "FL 3"
			And I fill in "address[city]" with "Boston"
		Given I set id for ".state"
			And I select "32" in "#blurclick"
			And I fill in "address[postcode]" with "02210"
			And I fill in "address[telephone]" with "6052223256"
			And I click on ".headline .cancel"
		Then I should see "Payment method"
		When I click on ".vi"
		Then I should see "Card Number"
			And I fill in "payment[card_number]" with "4111111111111111"
			And I fill in "payment[card_code]" with "458"
		Given I set id for ".expmonth"
			And I select "10" in "#blurclick"
		Given I set id1 for ".expmonth"
			And I select "2024" in "#blurclick1"